baseURL = "https://openencoder.com"
languageCode = 'en-us'
title = 'OpenEncoder'

[menu]
[[menu.main]]
name="Home"
url="/"
weight="1"

[[menu.main]]
name="Download"
url="/download"
weight="2"

[[menu.main]]
name="Presets"
url="/presets"
weight="3"

[[menu.main]]
name="Documentation"
url="/docs"
weight="4"

[[menu.main]]
name="About"
url="/about"
weight="5"
